<a href="https://colab.research.google.com/github/kareemrb27/Lab2.1/blob/master/Jan_27_%5BDemo_ML_Mini_Projects%5D.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
# Multi Category/Label Columns
l = [['t1'],['t1','t2'],['t2','t3']]
l

[['t1'], ['t1', 't2'], ['t2', 't3']]

In [ ]:
from mlxtend.preprocessing import TransactionEncoder
te = TransactionEncoder()
te.fit(l) #Extract all the unique/labels

TransactionEncoder()

In [ ]:
te.columns_

['t1', 't2', 't3']

In [ ]:
te.transform(l).astype(int)

array([[1, 0, 0],
       [1, 1, 0],
       [0, 1, 1]])

In [ ]:
pd.DataFrame(te.transform(l).astype(int), columns = te.columns_)

t1  t2  t3
0   1   0   0
1   1   1   0
2   0   1   1

In [ ]:
# Custom Function
l

[['t1'], ['t1', 't2'], ['t2', 't3']]

In [ ]:
categories = []
for i in l:
  categories.extend(i)

categories

['t1', 't1', 't2', 't2', 't3']

In [ ]:
list(set(categories))

['t2', 't3', 't1']

In [ ]:
df = pd.DataFrame([], columns = list(set(categories)))
df

Empty DataFrame
Columns: [t2, t3, t1]
Index: []

In [ ]:
for i in range(len(l)):
  for j in l[i]:
    df.loc[i, j] = 1

df

t2   t3   t1
0  NaN  NaN    1
1    1  NaN    1
2    1    1  NaN

In [ ]:
l

[['t1'], ['t1', 't2'], ['t2', 't3']]

In [ ]:
df.fillna(0)

<ipython-input-16-0979152f11c1>:1: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df.fillna(0)


t2  t3  t1
0   0   0   1
1   1   0   1
2   1   1   0

In [ ]:
# sklearn MultiLabelBinarizer...

from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer()
# The input to cv has to be a collection of strings
l

[['t1'], ['t1', 't2'], ['t2', 't3']]

In [ ]:
data = []
for i in l:
  data.append(' '.join(i))

In [ ]:
data

['t1', 't1 t2', 't2 t3']

In [ ]:
cv.fit(data)


CountVectorizer()

In [ ]:
cv.vocabulary_

{'t1': 0, 't2': 1, 't3': 2}

In [ ]:
cv.transform(data).toarray()

array([[1, 0, 0],
       [1, 1, 0],
       [0, 1, 1]])

In [ ]:
pd.DataFrame(cv.transform(data).toarray(), columns = cv.vocabulary_)

t1  t2  t3
0   1   0   0
1   1   1   0
2   0   1   1

In [ ]:
l

[['t1'], ['t1', 't2'], ['t2', 't3']]

In [ ]:
text = '''We’ve trained a model called ChatGPT which interacts in a conversational way. The dialogue format makes it possible for ChatGPT to answer followup questions, admit its mistakes, challenge incorrect premises, and reject inappropriate requests.

ChatGPT is a sibling model to InstructGPT⁠, which is trained to follow an instruction in a prompt and provide a detailed response.'''

In [ ]:
text

'We’ve trained a model called ChatGPT which interacts in a conversational way. The dialogue format makes it possible for ChatGPT to answer followup questions, admit its mistakes, challenge incorrect premises, and reject inappropriate requests.\n\nChatGPT is a sibling model to InstructGPT\u2060, which is trained to follow an instruction in a prompt and provide a detailed response.'

In [ ]:
# Naive way to extract words
text.split(' ')

['We’ve',
 'trained',
 'a',
 'model',
 'called',
 'ChatGPT',
 'which',
 'interacts',
 'in',
 'a',
 'conversational',
 'way.',
 'The',
 'dialogue',
 'format',
 'makes',
 'it',
 'possible',
 'for',
 'ChatGPT',
 'to',
 'answer',
 'followup',
 'questions,',
 'admit',
 'its',
 'mistakes,',
 'challenge',
 'incorrect',
 'premises,',
 'and',
 'reject',
 'inappropriate',
 'requests.\n\nChatGPT',
 'is',
 'a',
 'sibling',
 'model',
 'to',
 'InstructGPT\u2060,',
 'which',
 'is',
 'trained',
 'to',
 'follow',
 'an',
 'instruction',
 'in',
 'a',
 'prompt',
 'and',
 'provide',
 'a',
 'detailed',
 'response.']

In [ ]:
!pip install nltk

In [ ]:
import nltk
nltk.download('punkt_tab') # Tokenizer

[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt_tab.zip.


True

In [ ]:
from nltk import sent_tokenize
sent_tokenize(text)

['We’ve trained a model called ChatGPT which interacts in a conversational way.',
 'The dialogue format makes it possible for ChatGPT to answer followup questions, admit its mistakes, challenge incorrect premises, and reject inappropriate requests.',
 'ChatGPT is a sibling model to InstructGPT\u2060, which is trained to follow an instruction in a prompt and provide a detailed response.']

In [ ]:
from nltk import word_tokenize
word_tokenize(text)

['We',
 '’',
 've',
 'trained',
 'a',
 'model',
 'called',
 'ChatGPT',
 'which',
 'interacts',
 'in',
 'a',
 'conversational',
 'way',
 '.',
 'The',
 'dialogue',
 'format',
 'makes',
 'it',
 'possible',
 'for',
 'ChatGPT',
 'to',
 'answer',
 'followup',
 'questions',
 ',',
 'admit',
 'its',
 'mistakes',
 ',',
 'challenge',
 'incorrect',
 'premises',
 ',',
 'and',
 'reject',
 'inappropriate',
 'requests',
 '.',
 'ChatGPT',
 'is',
 'a',
 'sibling',
 'model',
 'to',
 'InstructGPT\u2060',
 ',',
 'which',
 'is',
 'trained',
 'to',
 'follow',
 'an',
 'instruction',
 'in',
 'a',
 'prompt',
 'and',
 'provide',
 'a',
 'detailed',
 'response',
 '.']

In [ ]:
# Decontract text
# We've --> We have


# Decontracting text involves expanding contractions into their full forms.
def decontract_text(text):

    # decontract text

    text = re.sub(r"won't", "will not", text)
    text = re.sub(r"we’ve", "we have", text)
    text = re.sub(r"can\'t", "can not", text)

    text = re.sub(r"n\'t", " not", text)
    text = re.sub(r"\'re", " are", text)
    text = re.sub(r"\'s", " is", text)
    text = re.sub(r"\'d", " would", text)
    text = re.sub(r"\'ll", " will", text)
    text = re.sub(r"\'t", " not", text)
    text = re.sub(r"\'ve", " have", text)
    text = re.sub(r"\'m", " am", text)

    return text

In [ ]:
import re
decontract_text(text.lower())

'we have trained a model called chatgpt which interacts in a conversational way. the dialogue format makes it possible for chatgpt to answer followup questions, admit its mistakes, challenge incorrect premises, and reject inappropriate requests.\n\nchatgpt is a sibling model to instructgpt\u2060, which is trained to follow an instruction in a prompt and provide a detailed response.'

In [ ]:
text = text.lower().replace('\n', ' ')
text.lower().replace('\u2060,', ' ')

'we’ve trained a model called chatgpt which interacts in a conversational way. the dialogue format makes it possible for chatgpt to answer followup questions, admit its mistakes, challenge incorrect premises, and reject inappropriate requests.  chatgpt is a sibling model to instructgpt  which is trained to follow an instruction in a prompt and provide a detailed response.'

In [ ]:
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.


True

In [ ]:
from nltk.corpus import stopwords
sw = stopwords.words('english')
sw # Generic stopwords

['i',
 'me',
 'my',
 'myself',
 'we',
 'our',
 'ours',
 'ourselves',
 'you',
 "you're",
 "you've",
 "you'll",
 "you'd",
 'your',
 'yours',
 'yourself',
 'yourselves',
 'he',
 'him',
 'his',
 'himself',
 'she',
 "she's",
 'her',
 'hers',
 'herself',
 'it',
 "it's",
 'its',
 'itself',
 'they',
 'them',
 'their',
 'theirs',
 'themselves',
 'what',
 'which',
 'who',
 'whom',
 'this',
 'that',
 "that'll",
 'these',
 'those',
 'am',
 'is',
 'are',
 'was',
 'were',
 'be',
 'been',
 'being',
 'have',
 'has',
 'had',
 'having',
 'do',
 'does',
 'did',
 'doing',
 'a',
 'an',
 'the',
 'and',
 'but',
 'if',
 'or',
 'because',
 'as',
 'until',
 'while',
 'of',
 'at',
 'by',
 'for',
 'with',
 'about',
 'against',
 'between',
 'into',
 'through',
 'during',
 'before',
 'after',
 'above',
 'below',
 'to',
 'from',
 'up',
 'down',
 'in',
 'out',
 'on',
 'off',
 'over',
 'under',
 'again',
 'further',
 'then',
 'once',
 'here',
 'there',
 'when',
 'where',
 'why',
 'how',
 'all',
 'any',
 'both',
 'each

In [ ]:
len(sw)

179

In [ ]:
sw.extend(['?', ',', "'", '"', '.'])
sw

['i',
 'me',
 'my',
 'myself',
 'we',
 'our',
 'ours',
 'ourselves',
 'you',
 "you're",
 "you've",
 "you'll",
 "you'd",
 'your',
 'yours',
 'yourself',
 'yourselves',
 'he',
 'him',
 'his',
 'himself',
 'she',
 "she's",
 'her',
 'hers',
 'herself',
 'it',
 "it's",
 'its',
 'itself',
 'they',
 'them',
 'their',
 'theirs',
 'themselves',
 'what',
 'which',
 'who',
 'whom',
 'this',
 'that',
 "that'll",
 'these',
 'those',
 'am',
 'is',
 'are',
 'was',
 'were',
 'be',
 'been',
 'being',
 'have',
 'has',
 'had',
 'having',
 'do',
 'does',
 'did',
 'doing',
 'a',
 'an',
 'the',
 'and',
 'but',
 'if',
 'or',
 'because',
 'as',
 'until',
 'while',
 'of',
 'at',
 'by',
 'for',
 'with',
 'about',
 'against',
 'between',
 'into',
 'through',
 'during',
 'before',
 'after',
 'above',
 'below',
 'to',
 'from',
 'up',
 'down',
 'in',
 'out',
 'on',
 'off',
 'over',
 'under',
 'again',
 'further',
 'then',
 'once',
 'here',
 'there',
 'when',
 'where',
 'why',
 'how',
 'all',
 'any',
 'both',
 'each

In [ ]:
for i in word_tokenize(text):
  if i not in sw:
    print(i)# non-stopwords

’
trained
model
called
chatgpt
interacts
conversational
way
dialogue
format
makes
possible
chatgpt
answer
followup
questions
admit
mistakes
challenge
incorrect
premises
reject
inappropriate
requests
chatgpt
sibling
model
instructgpt⁠
trained
follow
instruction
prompt
provide
detailed
response


In [ ]:
from nltk.stem import SnowballStemmer
ss = SnowballStemmer('english')
ss.stem('increases')

'increas'

In [ ]:
sw.append("’")
for i in word_tokenize(text):
  if i not in sw:
    print(i, ss.stem(i))# non-stopwords

trained train
model model
called call
chatgpt chatgpt
interacts interact
conversational convers
way way
dialogue dialogu
format format
makes make
possible possibl
chatgpt chatgpt
answer answer
followup followup
questions question
admit admit
mistakes mistak
challenge challeng
incorrect incorrect
premises premis
reject reject
inappropriate inappropri
requests request
chatgpt chatgpt
sibling sibl
model model
instructgpt⁠ instructgpt⁠
trained train
follow follow
instruction instruct
prompt prompt
provide provid
detailed detail
response respons


In [ ]:
sw.append("’")
final_words = []
for i in word_tokenize(text):
  if i not in sw:
    final_words.append(ss.stem(i))# non-stopwords

In [ ]:
' '.join(final_words)

'train model call chatgpt interact convers way dialogu format make possibl chatgpt answer followup question admit mistak challeng incorrect premis reject inappropri request chatgpt sibl model instructgpt\u2060 train follow instruct prompt provid detail respons'

In [ ]:
doc = ' '.join(final_words)
cv.fit([doc])

CountVectorizer()

In [ ]:
cv.vocabulary_

{'train': 28,
 'model': 18,
 'call': 2,
 'chatgpt': 4,
 'interact': 15,
 'convers': 5,
 'way': 29,
 'dialogu': 7,
 'format': 10,
 'make': 16,
 'possibl': 19,
 'answer': 1,
 'followup': 9,
 'question': 23,
 'admit': 0,
 'mistak': 17,
 'challeng': 3,
 'incorrect': 12,
 'premis': 20,
 'reject': 24,
 'inappropri': 11,
 'request': 25,
 'sibl': 27,
 'instructgpt': 14,
 'follow': 8,
 'instruct': 13,
 'prompt': 21,
 'provid': 22,
 'detail': 6,
 'respons': 26}

In [ ]:
sorted(cv.vocabulary_)

['admit',
 'answer',
 'call',
 'challeng',
 'chatgpt',
 'convers',
 'detail',
 'dialogu',
 'follow',
 'followup',
 'format',
 'inappropri',
 'incorrect',
 'instruct',
 'instructgpt',
 'interact',
 'make',
 'mistak',
 'model',
 'possibl',
 'premis',
 'prompt',
 'provid',
 'question',
 'reject',
 'request',
 'respons',
 'sibl',
 'train',
 'way']

In [ ]:
pd.DataFrame(cv.transform([doc]).toarray(), columns = sorted(cv.vocabulary_))

admit  answer  call  challeng  chatgpt  convers  detail  dialogu  follow  \
0      1       1     1         1        3        1       1        1       1   

   followup  ...  premis  prompt  provid  question  reject  request  respons  \
0         1  ...       1       1       1         1       1        1        1   

   sibl  train  way  
0     1      2    1  

[1 rows x 30 columns]

In [ ]:
doc

'train model call chatgpt interact convers way dialogu format make possibl chatgpt answer followup question admit mistak challeng incorrect premis reject inappropri request chatgpt sibl model instructgpt\u2060 train follow instruct prompt provid detail respons'

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer
tv = TfidfVectorizer()
tv.fit_transform([doc]).toarray()

array([[0.15075567, 0.15075567, 0.15075567, 0.15075567, 0.45226702,
        0.15075567, 0.15075567, 0.15075567, 0.15075567, 0.15075567,
        0.15075567, 0.15075567, 0.15075567, 0.15075567, 0.15075567,
        0.15075567, 0.15075567, 0.15075567, 0.30151134, 0.15075567,
        0.15075567, 0.15075567, 0.15075567, 0.15075567, 0.15075567,
        0.15075567, 0.15075567, 0.15075567, 0.30151134, 0.15075567]])

In [ ]:
pd.DataFrame(tv.fit_transform([doc]).toarray(), columns = sorted(tv.vocabulary_))

admit    answer      call  challeng   chatgpt   convers    detail  \
0  0.150756  0.150756  0.150756  0.150756  0.452267  0.150756  0.150756   

    dialogu    follow  followup  ...    premis    prompt    provid  question  \
0  0.150756  0.150756  0.150756  ...  0.150756  0.150756  0.150756  0.150756   

     reject   request   respons      sibl     train       way  
0  0.150756  0.150756  0.150756  0.150756  0.301511  0.150756  

[1 rows x 30 columns]

In [ ]:
!pip install pycaret

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 60.4/60.4 kB 2.5 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 169.6/169.6 kB 6.4 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
INFO: pip is looking at multiple versions of category-encoders to determine which version is compatible with other requirements. This could take a while.
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 0.0/486.1 kB ? eta -:--:--